
[build]
    functions = "lambda"

[context.develop.environment]
  GATSBY_REDIRECT_URI = https://develop--visindavoka.netlify.app/
  GATSBY_AUTH0_CLIENTID = tGyFpWhfmerJZ61Zslmzp4WYQidlLRiv
  GATSBY_AUTH0_DOMAIN = luttaka.eu.auth0.com
  GATSBY_PUBLIC_URL = https://develop--visindavoka.netlify.app/

[context.master.environment]
  GATSBY_REDIRECT_URI = https://vísindavøka.fo/
  GATSBY_AUTH0_CLIENTID = tGyFpWhfmerJZ61Zslmzp4WYQidlLRiv
  GATSBY_AUTH0_DOMAIN = luttaka.eu.auth0.com
  GATSBY_PUBLIC_URL = https://vísindavøka.fo/
